name: Node.js CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]
    
env:
  VUE_APP_BASE_URL: https://portafolio-backend-4or0.onrender.com
  
jobs:
  build:
    permissions:
      contents: read
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    runs-on: ubuntu-latest
      
    steps:
    - name: variable de entorno
      run: echo "VUE_APP_BASE_URL, $VUE_APP_BASE_URL"
      
    - uses: actions/checkout@v4
    
    - name: Instalar node
      uses: actions/setup-node@v3
      with:
        node-version: 18 # O la versión que uses en tu proyecto local
        cache: 'yarn'    # Esto acelera el proceso guardando en caché las dependencias
        
    - name: Instalar dependencias con Yarn
      run: yarn install --frozen-lockfile
      
    - name: Construir proyecto
      run: yarn build
      
    - name: Subir artefacto
      uses: actions/upload-pages-artifact@v3.0.1
      with:
        path: ./dist
        
    - name: Despliegue de la app
      uses: actions/deploy-pages@v4.0.5
